package org.civis.blockchain.sporttrakerimpact.strava.model

data class DetailedActivity(
        val description: String? = null,
        val photos: PhotosSummary? = null,
        val gear: SummaryGear? = null,
        val calories: Float? = null,
        val segmentEfforts: Array<DetailedSegmentEffort>? = null,
        val deviceName: String? = null,
        val embedToken: String? = null,
        val splitsMetric: Array<Split>? = null,
        val splitsStandard: Array<Split>? = null, val laps: Array<Lap>? = null,
        val bestEfforts: Array<DetailedSegmentEffort>? = null,
        val externalId: String? = null,
        val uploadId: Long? = null, val athlete: MetaAthlete? = null,
        val name: String? = null,
        val distance: Float? = null,
        val movingTime: Int? = null,
        val elapsedTime: Int? = null,
        val totalElevationGain: Float? = null,
        val elevHigh: Float? = null,
        val elevLow: Float? = null, val type: ActivityType? = null,
        val startDate: java.time.LocalDateTime? = null,
        val startDateLocal: java.time.LocalDateTime? = null,
        val timezone: String? = null,
        val startLatlng: LatLng? = null,
        val endLatlng: LatLng? = null,
        val achievementCount: Int? = null,
        val kudosCount: Int? = null,
        val commentCount: Int? = null,
        val athleteCount: Int? = null,
        val photoCount: Int? = null,
        val totalPhotoCount: Int? = null,
        val map: PolylineMap? = null,
        val trainer: Boolean? = null,
        val commute: Boolean? = null,
        val manual: Boolean? = null,
        val `private`: Boolean? = null,
        val flagged: Boolean? = null,
        val workoutType: Int? = null,
        val averageSpeed: Float? = null,
        val maxSpeed: Float? = null,
        val hasKudoed: Boolean? = null,
        val gearId: String? = null,
        val kilojoules: Float? = null,
        val averageWatts: Float? = null,
        val deviceWatts: Boolean? = null,
        val maxWatts: Int? = null,
        val weightedAverageWatts: Int? = null
) {
}
