package org.civis.blockchain.sporttrakerimpact.strava.model

import com.fasterxml.jackson.annotation.JsonAutoDetect
import com.fasterxml.jackson.annotation.JsonProperty


//{
//    "resource_state": 2,
//    "athlete": {
//      "id": 42468774,
//      "resource_state": 1
//    },
//    "name": "Marche matinale",
//    "distance": 2137.9,
//    "moving_time": 1443,
//    "elapsed_time": 1752,
//    "total_elevation_gain": 19.1,
//    "type": "Walk",
//    "id": 2405722271,
//    "external_id": "4cf0931f8e8244628a16606376b0b886",
//    "upload_id": 2557730239,
//    "start_date": "2019-05-29T06:37:22Z",
//    "start_date_local": "2019-05-29T08:37:22Z",
//    "timezone": "(GMT+01:00) Europe/Paris",
//    "utc_offset": 7200.0,
//    "start_latlng": [43.61, 3.87],
//    "end_latlng": [43.6, 3.88],
//    "location_city": null,
//    "location_state": null,
//    "location_country": null,
//    "start_latitude": 43.61,
//    "start_longitude": 3.87,
//    "achievement_count": 0,
//    "kudos_count": 0,
//    "comment_count": 0,
//    "athlete_count": 1,
//    "photo_count": 0,
//    "map": {
//      "id": "a2405722271",
//      "summary_polyline": "yieiG_qrVFRFDBGNGBDTJd@d@FBHH?FDOFML[@[Hu@AQRiA@SCU?QL[TaB@c@?o@DCHY@I?YFYAWDQL]Bm@LWNIJBFADEXFRCDEBSBGRIG??GHi@LCf@EL@THbB[KJDD@JCBBHBFJFPBDAVAXK`@GHEF?PHD?ZOR?HED?\\ODIPKXI\\O\\c@j@]HW^OL?LEFKHER[|AmBBINJHMF@BE?GBUAGPI^IFWJUB[HWFEd@aABe@NST_ANOLEDEV}@DUHO?GF]Ac@BQXm@DEF@JHHGHDAFDNH@BFDABDD@BDBQDC@OHOBOLK@MJGD?LWHW^K`@AXLLBDBN?D?BELEL?JGJUBo@BED?JHPGLg@R_@JW@KEC@I`@{@VSb@q@HU\\[LWLMD?VPRFDF]dAO@AKDVBEBBCFOCEEKc@DBBHD@",
//      "resource_state": 2
//    },
//    "trainer": false,
//    "commute": false,
//    "manual": false,
//    "private": false,
//    "visibility": "everyone",
//    "flagged": false,
//    "gear_id": null,
//    "from_accepted_tag": false,
//    "average_speed": 1.482,
//    "max_speed": 6.0,
//    "has_heartrate": false,
//    "heartrate_opt_out": false,
//    "display_hide_heartrate_option": false,
//    "elev_high": 53.8,
//    "elev_low": 30.3,
//    "pr_count": 0,
//    "total_photo_count": 0,
//    "has_kudoed": false
//}

data class SummaryActivity (
        val resource_state: Int? = null,
        val externalId: String? = null,    
        val uploadId: Long? = null,    
        val athlete: MetaAthlete? = null,    
        val name: String? = null,    
        val distance: Float? = null,
        val movingTime: Int? = null,
        val elapsedTime: Long? = null,
        val totalElevationGain: Float? = null,    
        val elevHigh: Float? = null,    
        val elevLow: Float? = null,    
        val type: ActivityType? = null,    
        val startDate: java.time.LocalDateTime? = null,    
        val startDateLocal: java.time.LocalDateTime? = null,    
        val timezone: String? = null,    
        val startLatlng: LatLng? = null,    
        val endLatlng: LatLng? = null,    
        val achievementCount: Int? = null,    
        val kudosCount: Int? = null,    
        val commentCount: Int? = null,    
        val athleteCount: Int? = null,    
        val photoCount: Int? = null,    
        val totalPhotoCount: Int? = null,    
        val map: PolylineMap? = null,    
        val trainer: Boolean? = null,    
        val commute: Boolean? = null,    
        val manual: Boolean? = null,    
        val `private`: Boolean? = null,    
        val flagged: Boolean? = null,    
        val workoutType: Int? = null,    
        val averageSpeed: Float? = null,    
        val maxSpeed: Float? = null,    
        val hasKudoed: Boolean? = null,   
        val gearId: String? = null,    
        val kilojoules: Float? = null,    
        val averageWatts: Float? = null,    
        val deviceWatts: Boolean? = null,    
        val maxWatts: Int? = null,    
        val weightedAverageWatts: Int? = null,    
        val id: Long? = null,
        val utcOffset: Float? = null,
        val locationCity: String? = null
        ) {
}
